version: "3.8"

volumes:
  bio-mysql-data:
    driver: local

  bio-redis-data:
    driver: local

services:
  bio-php:
    build: ./docker/php
    container_name: bio-php
    working_dir: /var/www/app
    command: sh -c "composer install && composer watch"
    ports:
      - "7010:9501"
    volumes:
      - ./:/var/www/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - bio-mysql
      - bio-mailcatcher
    links:
      - "bio-mysql:database"
      - "bio-mailcatcher:mail"

  bio-mysql:
    build: ./docker/mysql
    container_name: bio-mysql
    volumes:
      - bio-mysql-data:/var/lib/mysql
    ports:
      - "7011:3306"
    environment:
      - "MYSQL_DATABASE=bio"
      - "MYSQL_ROOT_PASSWORD=root"

  bio-mailcatcher:
    image: dockage/mailcatcher:0.8.2
    container_name: bio-mailcatcher
    ports:
      - "7013:1080"
      - "7014:1025"
